name: build-docker-images
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: mvkessel
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build Docker image
        run: "docker build -t mvkessel/unsafe-image ."
      - name: Push image
        run: "docker push mvkessel/unsafe-image"
  