# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  search:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          FILES=$(find images -name Dockerfile | sed -e 's#^images/##' -e 's#/Dockerfile$##' | jq -Rsc '. / "\n" - [""]')
          echo $FILES
          echo "::set-output name=matrix::$FILES"

  echo:
    name: Build and check ${{ matrix.image }}
    needs: search
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{fromJSON(needs.search.outputs.matrix)}}
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t mvkessel/${{matrix.image}}:${{ github.sha }} images/${{matrix.image}}
      - name: Run Trivy vulnerability scanner (informative)
        uses: aquasecurity/trivy-action@2a2157eb22c08c9a1fac99263430307b8d1bc7a2
        with:
          image-ref: 'mvkessel/${{matrix.image}}:${{ github.sha }}'
          format: table
      - name: Run Trivy vulnerability scanner (enforcing)
        uses: aquasecurity/trivy-action@2a2157eb22c08c9a1fac99263430307b8d1bc7a2
        with:
          image-ref: 'mvkessel/${{matrix.image}}:${{ github.sha }}'
          format: table
          severity: 'CRITICAL'
          exit-code: 1
          # format: 'template'
          # template: '@/contrib/sarif.tpl'
          # output: 'trivy-results.sarif'
      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v1
      #   with:
      #     sarif_file: 'trivy-results.sarif'
